// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/bank/deposits": {
            "get": {
                "description": "Lists ` + "`" + `Deposited` + "`" + ` events stored by the local bank indexer. Optional filter by user wallet.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bank"
                ],
                "summary": "Bank deposits (indexed DB)",
                "parameters": [
                    {
                        "maximum": 200,
                        "minimum": 1,
                        "type": "integer",
                        "default": 50,
                        "description": "Max rows (default 50, max 200)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by user address (0x...), case-insensitive match",
                        "name": "user",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.BankDepositsResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorJSON"
                        }
                    },
                    "503": {
                        "description": "database not configured",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorJSON"
                        }
                    }
                }
            }
        },
        "/api/bank/subgraph/deposits": {
            "get": {
                "description": "Queries the configured subgraph for ` + "`" + `Deposited` + "`" + ` entities. Requires SUBGRAPH_URL (and optional SUBGRAPH_API_KEY).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bank"
                ],
                "summary": "Bank deposits (The Graph)",
                "parameters": [
                    {
                        "type": "string",
                        "example": "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045",
                        "description": "Wallet address (0x-prefixed)",
                        "name": "user",
                        "in": "query",
                        "required": true
                    },
                    {
                        "maximum": 200,
                        "minimum": 1,
                        "type": "integer",
                        "default": 50,
                        "description": "Max rows (default 50, max 200)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.SubgraphDepositsResp"
                        }
                    },
                    "400": {
                        "description": "missing or invalid user",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorJSON"
                        }
                    },
                    "502": {
                        "description": "subgraph HTTP or parse error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorJSON"
                        }
                    },
                    "503": {
                        "description": "subgraph not configured",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorJSON"
                        }
                    }
                }
            }
        },
        "/api/bank/subgraph/withdrawals": {
            "get": {
                "description": "Queries the configured subgraph for ` + "`" + `Withdrawn` + "`" + ` entities. Requires SUBGRAPH_URL (and optional SUBGRAPH_API_KEY).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bank"
                ],
                "summary": "Bank withdrawals (The Graph)",
                "parameters": [
                    {
                        "type": "string",
                        "example": "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045",
                        "description": "Wallet address (0x-prefixed)",
                        "name": "user",
                        "in": "query",
                        "required": true
                    },
                    {
                        "maximum": 200,
                        "minimum": 1,
                        "type": "integer",
                        "default": 50,
                        "description": "Max rows (default 50, max 200)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.SubgraphWithdrawalsResp"
                        }
                    },
                    "400": {
                        "description": "missing or invalid user",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorJSON"
                        }
                    },
                    "502": {
                        "description": "subgraph HTTP or parse error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorJSON"
                        }
                    },
                    "503": {
                        "description": "subgraph not configured",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorJSON"
                        }
                    }
                }
            }
        },
        "/api/bank/withdrawals": {
            "get": {
                "description": "Lists ` + "`" + `Withdrawn` + "`" + ` events stored by the local bank indexer. Optional filter by user wallet.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "bank"
                ],
                "summary": "Bank withdrawals (indexed DB)",
                "parameters": [
                    {
                        "maximum": 200,
                        "minimum": 1,
                        "type": "integer",
                        "default": 50,
                        "description": "Max rows (default 50, max 200)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by user address (0x...), case-insensitive match",
                        "name": "user",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.BankWithdrawalsResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorJSON"
                        }
                    },
                    "503": {
                        "description": "database not configured",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorJSON"
                        }
                    }
                }
            }
        },
        "/api/chain/status": {
            "get": {
                "description": "When ETH_RPC_URL is configured and dial succeeds, returns ` + "`" + `configured: true` + "`" + ` and ` + "`" + `chain_id` + "`" + `. Otherwise ` + "`" + `configured: false` + "`" + ` and a short message.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "chain"
                ],
                "summary": "Chain status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.ChainStatusResp"
                        }
                    },
                    "503": {
                        "description": "e.g. chain id read failed",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorJSON"
                        }
                    }
                }
            }
        },
        "/api/code-pulse/actions/check": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "code-pulse"
                ],
                "summary": "Action pre-check",
                "parameters": [
                    {
                        "description": "Action check request",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/codepulse.ActionCheckReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/codepulse.ActionCheckResp"
                        }
                    }
                }
            }
        },
        "/api/code-pulse/admin/dashboard": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "code-pulse"
                ],
                "summary": "Admin dashboard",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/code-pulse/admin/platform-funds": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "code-pulse-admin"
                ],
                "summary": "Platform funds overview",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/code-pulse/admin/proposal-initiators": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "code-pulse-admin"
                ],
                "summary": "List proposal initiators",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "code-pulse-admin"
                ],
                "summary": "Add proposal initiator",
                "parameters": [
                    {
                        "description": "{ address: string }",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/code-pulse/admin/proposal-initiators/{address}": {
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "code-pulse-admin"
                ],
                "summary": "Remove proposal initiator",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Wallet address",
                        "name": "address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/code-pulse/admin/sync-status": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "code-pulse-admin"
                ],
                "summary": "Sync status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/code-pulse/campaigns": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "code-pulse"
                ],
                "summary": "List campaigns",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by state",
                        "name": "state",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Filter by proposal_id",
                        "name": "proposal_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by organizer address",
                        "name": "organizer",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by developer (joined)",
                        "name": "developer",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by contributor (joined)",
                        "name": "contributor",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort: launched_at_desc (default), deadline_at_asc",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/code-pulse/campaigns/{campaignId}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "code-pulse"
                ],
                "summary": "Campaign detail",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Campaign ID",
                        "name": "campaignId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorJSON"
                        }
                    }
                }
            }
        },
        "/api/code-pulse/campaigns/{campaignId}/contributions": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "code-pulse"
                ],
                "summary": "Campaign contributions",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Campaign ID",
                        "name": "campaignId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Filter by contributor address",
                        "name": "contributor",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort: amount_desc (default), latest",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/code-pulse/campaigns/{campaignId}/timeline": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "code-pulse"
                ],
                "summary": "Campaign timeline",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Campaign ID",
                        "name": "campaignId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/code-pulse/config": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "code-pulse"
                ],
                "summary": "Code Pulse config",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/code-pulse/contributors/{address}/dashboard": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "code-pulse"
                ],
                "summary": "Contributor dashboard",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Wallet address",
                        "name": "address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/code-pulse/developers/{address}/dashboard": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "code-pulse"
                ],
                "summary": "Developer dashboard",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Wallet address",
                        "name": "address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/code-pulse/initiators/{address}/dashboard": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "code-pulse"
                ],
                "summary": "Initiator dashboard",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Wallet address",
                        "name": "address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/code-pulse/proposals": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "code-pulse"
                ],
                "summary": "List proposals",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Filter by status",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by organizer address",
                        "name": "organizer",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by round_review_state",
                        "name": "review_state",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size (default 20, max 100)",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Sort: submitted_at_desc (default), submitted_at_asc",
                        "name": "sort",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/code-pulse/proposals/{proposalId}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "code-pulse"
                ],
                "summary": "Proposal detail",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Proposal ID",
                        "name": "proposalId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorJSON"
                        }
                    }
                }
            }
        },
        "/api/code-pulse/proposals/{proposalId}/timeline": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "code-pulse"
                ],
                "summary": "Proposal timeline",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Proposal ID",
                        "name": "proposalId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/code-pulse/summary": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "code-pulse"
                ],
                "summary": "Code Pulse summary",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/code-pulse/tx/build": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "code-pulse"
                ],
                "summary": "Build transaction calldata",
                "parameters": [
                    {
                        "description": "Action + wallet + params",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/codepulse.TxBuildReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/code-pulse/tx/submit": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "code-pulse"
                ],
                "summary": "Submit transaction (server-signed)",
                "parameters": [
                    {
                        "description": "Action + params",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/codepulse.TxBuildReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/code-pulse/tx/{attemptId}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "code-pulse"
                ],
                "summary": "Get transaction attempt",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Attempt ID",
                        "name": "attemptId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorJSON"
                        }
                    }
                }
            }
        },
        "/api/code-pulse/wallets/{address}/overview": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "code-pulse"
                ],
                "summary": "Wallet overview",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Wallet address (0x...)",
                        "name": "address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/contract/counter/count": {
            "post": {
                "description": "Sends an on-chain transaction calling ` + "`" + `count()` + "`" + ` using ETH_PRIVATE_KEY. Request has **no body**.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "contract"
                ],
                "summary": "Counter increment (tx)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.CounterIncrementResp"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorJSON"
                        }
                    },
                    "502": {
                        "description": "transaction send error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorJSON"
                        }
                    },
                    "503": {
                        "description": "contract, RPC, or private key not configured",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorJSON"
                        }
                    }
                }
            }
        },
        "/api/contract/counter/value": {
            "get": {
                "description": "Reads ` + "`" + `get()` + "`" + ` from the configured counter contract (requires COUNTER_CONTRACT_ADDRESS and ETH_RPC_URL).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "contract"
                ],
                "summary": "Counter current value",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.CounterValueResp"
                        }
                    },
                    "502": {
                        "description": "RPC / contract call error",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorJSON"
                        }
                    },
                    "503": {
                        "description": "contract or RPC not configured",
                        "schema": {
                            "$ref": "#/definitions/handlers.ErrorJSON"
                        }
                    }
                }
            }
        },
        "/api/info": {
            "get": {
                "description": "Returns API name and version string.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "API info",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.APIInfoResp"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns JSON ` + "`" + `{ \"status\": \"ok\" }` + "`" + ` when the process is running.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.HealthResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "codepulse.ActionCheckReq": {
            "type": "object",
            "required": [
                "action",
                "wallet"
            ],
            "properties": {
                "action": {
                    "type": "string"
                },
                "campaign_id": {
                    "type": "integer"
                },
                "milestone_index": {
                    "type": "integer"
                },
                "params": {},
                "proposal_id": {
                    "type": "integer"
                },
                "wallet": {
                    "type": "string"
                }
            }
        },
        "codepulse.ActionCheckResp": {
            "type": "object",
            "properties": {
                "allowed": {
                    "type": "boolean"
                },
                "current_state": {
                    "type": "string"
                },
                "reason_code": {
                    "type": "string"
                },
                "reason_message": {
                    "type": "string"
                },
                "required_role": {
                    "type": "string"
                },
                "revert_error_args": {},
                "revert_error_name": {
                    "type": "string"
                }
            }
        },
        "codepulse.TxBuildReq": {
            "type": "object",
            "required": [
                "action",
                "wallet"
            ],
            "properties": {
                "action": {
                    "type": "string"
                },
                "params": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "wallet": {
                    "type": "string"
                }
            }
        },
        "handlers.APIInfoResp": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string",
                    "example": "go-chain API"
                },
                "version": {
                    "type": "string",
                    "example": "0.1.0"
                }
            }
        },
        "handlers.BankDepositsResp": {
            "type": "object",
            "properties": {
                "deposits": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.BankDeposit"
                    }
                }
            }
        },
        "handlers.BankWithdrawalsResp": {
            "type": "object",
            "properties": {
                "withdrawals": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.BankWithdrawal"
                    }
                }
            }
        },
        "handlers.ChainStatusResp": {
            "type": "object",
            "properties": {
                "chain_id": {
                    "type": "integer"
                },
                "configured": {
                    "type": "boolean"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "handlers.CounterIncrementResp": {
            "type": "object",
            "properties": {
                "tx_hash": {
                    "type": "string"
                }
            }
        },
        "handlers.CounterValueResp": {
            "type": "object",
            "properties": {
                "value": {
                    "type": "string"
                }
            }
        },
        "handlers.ErrorJSON": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "handlers.HealthResp": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "handlers.SubgraphDepositsResp": {
            "type": "object",
            "properties": {
                "deposits": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.SubgraphEventRow"
                    }
                },
                "source": {
                    "type": "string",
                    "example": "subgraph"
                }
            }
        },
        "handlers.SubgraphEventRow": {
            "type": "object",
            "properties": {
                "amount_raw": {
                    "type": "string"
                },
                "block_number": {
                    "type": "integer"
                },
                "block_time": {
                    "type": "string"
                },
                "subgraph_entity_id": {
                    "type": "string"
                },
                "token_address": {
                    "type": "string"
                },
                "tx_hash": {
                    "type": "string"
                },
                "user_address": {
                    "type": "string"
                }
            }
        },
        "handlers.SubgraphWithdrawalsResp": {
            "type": "object",
            "properties": {
                "source": {
                    "type": "string",
                    "example": "subgraph"
                },
                "withdrawals": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.SubgraphEventRow"
                    }
                }
            }
        },
        "models.BankDeposit": {
            "type": "object",
            "properties": {
                "amount_raw": {
                    "type": "string"
                },
                "block_number": {
                    "type": "integer"
                },
                "block_time": {
                    "type": "string"
                },
                "chain_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "log_index": {
                    "type": "integer"
                },
                "token_address": {
                    "type": "string"
                },
                "tx_hash": {
                    "type": "string"
                },
                "user_address": {
                    "type": "string"
                }
            }
        },
        "models.BankWithdrawal": {
            "type": "object",
            "properties": {
                "amount_raw": {
                    "type": "string"
                },
                "block_number": {
                    "type": "integer"
                },
                "block_time": {
                    "type": "string"
                },
                "chain_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "log_index": {
                    "type": "integer"
                },
                "token_address": {
                    "type": "string"
                },
                "tx_hash": {
                    "type": "string"
                },
                "user_address": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "go-chain API",
	Description:      "REST API: health, chain status, counter contract calls, bank ledger (PostgreSQL indexer + optional The Graph subgraph).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
